### ISSUE TITLE
build fails with Apple's clang 12 (from XCode 12)

### ISSUE THREAD

**Issue by dimpase** [gap-packages/cohomolo#27]
one gets things such as 
```
gcc -c -O -fno-builtin gpd.c 
gpd.c:37:7: error: implicit declaration of function 'gpprog' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  if (gpprog()== -1) exit(1);
      ^
1 error generated.
```
as XCode 12 is very strict w.r.t. implicit function decls.

**Comment by fingolfin** [comment]
I just tried this and could not reproduce the problem on an M1 Mac Mini. Please tell me some more details:
- which version of cohomolo?
- output of `sw_vers`
- output of `cc --version`

**Comment by dimpase** [comment]
oops, that was still with 1.6.8 (as in GAP 4.11.0).

**Comment by dimpase** [comment]
It appears that I basically did the same patching in https://github.com/sagemath/sage/blame/develop/build/pkgs/gap_packages/patches/cohomolo-gcc10.patch, 
few weeks after you added your patch. :man_facepalming:

**Comment by dimpase** [comment]
sorry for noise.
